name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.5.0
  TF_IN_AUTOMATION: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  BACKEND_RG: ${{ secrets.TFSTATE_RESOURCE_GROUP }}         # Example: tfstate-rg
  BACKEND_STORAGE: ${{ secrets.TFSTATE_STORAGE_ACCOUNT }}   # Example: tfstateglobal
  BACKEND_CONTAINER: ${{ secrets.TFSTATE_CONTAINER }}        # Example: tfstate

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init with Shared Backend
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.BACKEND_RG }}" \
            -backend-config="storage_account_name=${{ env.BACKEND_STORAGE }}" \
            -backend-config="container_name=${{ env.BACKEND_CONTAINER }}" \
            -backend-config="key=terraform.${{ github.event.inputs.environment }}.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars

      - name: Terraform Apply
        if: github.event.inputs.environment == github.event.inputs.environment
        run: terraform apply -var-file=${{ github.event.inputs.environment }}.tfvars -auto-approve
